### ISSUE TITLE
Missing NavigateAction.h

### ISSUE THREAD

**Issue by enricotoi** [fairf4x/move_quadcopter#3]
When trying to build the cloned repo catkin_make complains about a missing NavigateAction.h that can't be found in the repo at all.

"fatal error: move_quadcopter/NavigateAction.h: No such file or directory #include <move_quadcopter/NavigateAction.h>"

**Comment by fairf4x** [comment]
NavigateAction.h should be generated automatically - this should be done according to these lines in CMakeLists.txt:
```
add_action_files(DIRECTORY action
   FILES
   Navigate.action
)

generate_messages(DEPENDENCIES
  std_msgs
  geometry_msgs
  actionlib_msgs
)
```

I have verified this in my workspace. Resulting header files should be found in:
`my_workspace/devel/include/move_quadcopter`

Hope this helps at least to debug the issue.

**Comment by enricotoi** [comment]
I can find the lines you mentioned in the CMakeLists.txt, but it still doesn't build it with catkin_make. And there is nothing in the devel/include/move_quadcopter folder.

This is what the command line says when trying to build it. I haven't changed anything in the cloned files from the repo either.
![hector_move](https://user-images.githubusercontent.com/30490670/30849531-4e775fda-a2ab-11e7-86ce-47c5458335cf.jpg)

**Comment by fairf4x** [comment]
My output looks a bit different. I am using ROS kinetic.
It seems to me, that your catkin workspace is missing some paths - for example:
```
-- Using CATKIN_DEVEL_PREFIX: /home/fairfax/ROS/test_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/fairfax/ROS/test_ws/devel;/home/fairfax/ROS/bebop/devel;/home/fairfax/ROS/catkin_ws/devel;/opt/ros/kinetic
```
I always create workspaces using this script create_workspace.sh:
```
#!/bin/bash

HERE=`pwd`
WS_NAME=$1

if [ -n "$WS_NAME" ];
then
        mkdir -p $HERE/$WS_NAME/src
        cd $HERE/$WS_NAME/src
        catkin_init_workspace
        echo "===== CATKIN WORKSPACE INITIALIZED ====="
        cd $HERE/$WS_NAME/
        catkin_make
        echo "===== CATKIN MAKE CALLED ====="
fi
```
It should be called with one parameter - name of the workspace e.g.: `./create_workspace.sh WSNAME`
After you run it, it is necessary to call:`. WSNAME/devel/setup.bash`
to inicialize workspace in your current terminal. The command `roscd` should now get you in WSNAME/devel directory (just to verify it worked).
Then you can try to clone the repository in WSNAME/src and run `catkin_make` from WSNAME.

**Comment by enricotoi** [comment]
ROS wise I'm using Indigo.

So far I have always created my workspaces manually without a problem using the same commands that are in your script. 
But I'm unable to get to any of my workspaces with roscd, nor the one created with your script even if I run or source the devel/setup.bash. And the catkin_make still fails on the same problems.

I think the easiest way to solve all this would be if you just included the necessary .h files in the repository.

**Comment by fairf4x** [comment]
Ok. I have created branch indigo where you can find all the automatically generated header files in the `include` directory. Since I do not have ROS indigo, I can't test if it works. Good luck!

**Comment by enricotoi** [comment]
thank you, it built successfully now.
